#version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=user1'
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user1
      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - '8080:8080'
